### ISSUE TITLE
Is this gem still working?

### ISSUE THREAD

**Issue by christinec01** [Frylock13/image_searcher#1]
It was running yesterday, but today I'm getting a 500 errror. Any info you can provide would be awesome!

**Comment by terminaut** [comment]
@christinec01  Hey. I checked and it works. Well, it's just an API wrapper, so maybe some troubles with http://api.ababeen.com.

**Comment by ababeen** [comment]
Hi, This moktarul from ababeen-image-search team. Its working now. For any issue please reach out to us, ababeen135@gmail.com to make it world class free api. There was a issue with spam request to server and making slow. so we have over come that issue and also implemented memcache to improve performance
